server:
  port: 0

eureka:
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://localhost:8761/eureka

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: cos1234

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: mybatis-mapper/*.xml
  configuration.map-underscore-to-camel-case: true

logging:
  level:
    com.example.catalogservice: DEBUG

