server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/jeonghun/Desktop/IT/spring cloud/git-local-repo
          uri: https://github.com/Jeonghoon2/spring-cloud-config
          #프라이빗을 했을 경우
#          username:
#          password: